import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  modalContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 60,
    marginHorizontal: 6,
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#5cc1e0",
    paddingTop: 30,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0)",
  },
  input: {
    borderBottomWidth: 1.5,
    borderBottomColor: "#5cc1e0",
    padding: 16,
    fontSize: 20,
    borderRadius: 6,
    marginHorizontal: 2,
    marginVertical: 2,
    backgroundColor: "#f1f1f1",
  },
  rowinput: {
    borderBottomWidth: 1.5,
    borderBottomColor: "#5cc1e0",
    paddingHorizontal: 26,
    paddingVertical: 6,
    fontSize: 20,
    borderRadius: 6,
    marginHorizontal: 6,
    marginVertical: 2,
    backgroundColor: "#f1f1f1",
  },
  errorText: {
    color: "#ff5252",
    fontWeight: "bold",
    //marginBottom: 5,
    marginTop: 6,
    textAlign: "center",
    alignSelf: "center",
  },
  buttonContainer: {
    marginTop: 20,
    borderRadius: 6,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    gap: 10,
    marginBottom: 20,
  },
  button: {
    backgroundColor: "#f29400",
    padding: 10,
    margin: 15,
    width: 200,
    borderRadius: 10,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    alignSelf: "flex-start",
    paddingLeft: 20,
    marginBottom: 10,
    color: "#5cc1e0",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#f29400",
    marginBottom: 5,
  },
  text: {
    fontSize: 16,
    color: "black",
    marginBottom: 10,
  },
  carts: {
    backgroundColor: "#f1f1f1",
    elevation: 2,
    borderWidth: 1,
    padding: 10,
    marginVertical: 8,
    marginHorizontal: 16,
    borderRadius: 20,
  },
});

export const globalColors = {
  primary: "#5cc1e0",
  secondary: "#f29400",
  tertiary: "#656464",
  white: "#fff",
  black: "#000",
  gray: "#ccc",
  danger: "#ff5252",
  success: "#2b9348",
  warning: "#f77f00",
  info: "#3a86ff",
  light: "#f1f1f1",
  dark: "#333",
  bg: "#e8f4f8",
};
